# Generated by Django 5.2.7 on 2025-11-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_media_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_media_video',
            field=models.FileField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
