# Generated by Django 5.2.7 on 2025-11-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_hero_media_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='projects_carousel_interval',
            field=models.PositiveIntegerField(default=5, help_text='Seconds between slides for Featured Projects'),
        ),
    ]
