# Generated by Django 5.2.7 on 2025-11-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_audience_and_secondary_hero_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='process_graphic',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
