# Generated by Django 5.2.7 on 2025-11-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_process_graphic'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/icons/')),
                ('link_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Featured Service (Homepage)',
                'verbose_name_plural': 'Featured Services (Homepage)',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
