# Generated by Django 5.2.7 on 2025-11-08 10:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('CEO_MD', 'CEO/Managing Director'), ('COO', 'COO (Admin/Operations)'), ('CFO', 'CFO (Finance)'), ('CMO', 'Chief Marketing Officer')], max_length=16),
        ),
        migrations.CreateModel(
            name='StaffReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('CEO_MD', 'CEO/Managing Director'), ('COO', 'COO (Admin/Operations)'), ('CFO', 'CFO (Finance)'), ('CMO', 'Chief Marketing Officer')], max_length=12)),
                ('content', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='staff_reports/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('NEEDS_REVIEW', 'Needs Review')], default='SUBMITTED', max_length=14)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('operations_area', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('finance_category', models.CharField(blank=True, max_length=120)),
                ('reference_code', models.CharField(blank=True, max_length=120)),
                ('campaign_name', models.CharField(blank=True, max_length=160)),
                ('channel', models.CharField(blank=True, max_length=120)),
                ('strategic_focus', models.CharField(blank=True, max_length=160)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
