# Generated by Django 5.2.7 on 2025-11-08 11:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffprofile_role_staffreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffreport',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffreport',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='staff_reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffreport',
            name='report_type',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('SPECIAL', 'Special')], default='WEEKLY', max_length=10),
        ),
        migrations.CreateModel(
            name='StaffMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipients', models.ManyToManyField(blank=True, related_name='staff_messages_received', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='staff.staffreport')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
