# Generated by Django 5.2.7 on 2025-11-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
