# Generated by Django 5.2.7 on 2025-11-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teammember_options_teammember_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, null=True, max_length=120, unique=False),
        ),
    ]
