# Generated by Django 5.2.7 on 2025-11-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_teammember_contact_teammember_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
