# Generated by Django 5.2.7 on 2025-11-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_expertise',
            field=models.BooleanField(default=True),
        ),
    ]
